const imageSlide = [
    {
        url:'src/Images/margalla2.mp4',
    },
    {
        url:'src/Images/balochistan.mp4',
    },
    {
        url:'src/Images/bmosque.mp4',
    },
    {
        url:'src/Images/nathiagali3.mp4',
    },
    {
        url:'src/Images/gilgitbaltistan1.mp4',
    },
    {
        url:'src/Images/hiran.mp4',
    },
    {
        url:'src/Images/hbridge.mp4',
    },
    {
        url:'src/Images/khighway.mp4',
    },
    {
        url:'src/Images/kmountain.mp4',
    },
    {
        url:'src/Images/qtomb.mp4',
    },
    {
        url:'src/Images/deosaiplains1.mp4',
    },
    {
        url:'src/Images/minar.mp4',
    },
    {
        url:'src/Images/seaview.mp4',
    },
    {
        url:'src/Images/raikot.mp4',
    },
    {
        url:'src/Images/passu.mp4',
    },
    {
        url:'src/Images/kashmir.mp4',
    },
    {
        url:'src/Images/fmeadows.mp4',
    },
    {
        url:'src/Images/rupal.mp4',
    },
    {
        url:'src/Images/parsan.mp4',
    },
    {
        url:'src/Images/hunza.mp4',
    },
    {
        url:'src/Images/mitre.mp4',
    },
    {
        url:'src/Images/nangaparbat.mp4',
    },
    {
        url:'src/Images/karimabad.mp4',
    },
    {
        url:'src/Images/pcones.mp4',
    },
    {
        url:'src/Images/K2.mp4',
    },
];

export default imageSlide;
